# Generated by Django 4.2.6 on 2023-11-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_recipe_image'),
        ('users', '0002_customuser_favorite_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
