# Generated by Django 4.2.6 on 2023-11-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_image',
            field=models.ImageField(null=True, upload_to='static/images/meals/'),
        ),
    ]
